### ISSUE TITLE
Timeout value error on flow.finish

### ISSUE THREAD

**Issue by grzekru** [dropbox/dropbox-sdk-python#106] opened 2017-05-28 08:23 UTC
Python 2.7.13
urllib3==1.21.1
requests==2.16.5
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0

Works good on older requests version

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/dropbox/oauth.py", line 239, in finish
    return self._finish(code, None)
  File "/usr/lib/python2.7/site-packages/dropbox/oauth.py", line 119, in _finish
    resp = self.requests_session.post(url, data=params)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 570, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/lib/python2.7/site-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/lib/python2.7/site-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/site-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.

**Comment by 573** [comment] 2017-05-28 19:52
Same here:

 >>> dbx.users_get_current_account()
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/dropbox/base.py", line 2701, in users_get_current_account
    None,
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 249, in request
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 341, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 417, in request_json_string
    timeout=timeout,
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 570, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python3.6/site-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.

**Comment by greg-db** [comment] 2017-05-29 17:46
Thanks for writing in. We're looking into it. 

It looks like this started with some recent changes to the requests library, so as a workaround you can downgrade to requests v2.15.1.

**Comment by greg-db** [comment] 2017-05-29 20:31
It looks like this is fixed in requests v2.17.1, so please update to that and let me know if you're still seeing any issues.

**Closed by greg-db** 2017-05-29 20:31 UTC

**Comment by 573** [comment] 2017-05-30 19:53
Thanks @greg-db upgrading to requests==2.17.1 works. Confirmed.

**Comment by Susairaj** [comment] 2017-09-22 06:47
Thank you.....it works
