### ISSUE TITLE
Timeout when running updown.py

### ISSUE THREAD

**Issue by davesdere** [dropbox/dropbox-sdk-python#146] opened 2018-05-11 00:12 UTC
Running on Raspbian Stretch on a Pi Zero W with Python 3.5.
`python3 updown.py`
Gives me this
```
Dropbox folder name: Videos
Local directory: /home/pi/Jarvis/videos
Total elapsed time for list_folder: 0.079
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "updown.py", line 243, in <module>
    main()
  File "updown.py", line 68, in main
    listing = list_folder(dbx, folder, subfolder)
  File "updown.py", line 134, in list_folder
    res = dbx.files_list_folder(path)
  File "/usr/local/lib/python3.5/dist-packages/dropbox/base.py", line 1559, in files_list_folder
    None,
  File "/usr/local/lib/python3.5/dist-packages/dropbox/dropbox.py", line 272, in request
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/dropbox/dropbox.py", line 363, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/dropbox/dropbox.py", line 447, in request_json_string
    timeout=timeout,
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 588, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 303, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.

```

Any pointers?

**Comment by greg-db** [comment] 2018-05-11 15:15
This appears to be a duplicate of #106 or #114. Please check those out for more information.

In short though, upgrade the `requests` library to the latest version, currently v2.18.4.

**Closed by greg-db** 2018-05-11 15:15 UTC
Labels: duplicate
