### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'Timeout'  for python3.6

### ISSUE THREAD

**Issue by yufeiluo** [dropbox/dropbox-sdk-python#114] opened 2017-06-29 23:34 UTC
```
$ git clone git://github.com/dropbox/dropbox-sdk-python.git
$ cd dropbox-sdk-python
$ python setup.py install
>>> import dropbox
>>> dbx = dropbox.Dropbox("YOUR_ACCESS_TOKEN")
>>> dbx.users_get_current_account()
Traceback (most recent call last):
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/urllib3-1.21.1-py3.6.egg/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/debian8/dropbox-sdk-python/dropbox/base.py", line 3277, in users_get_current_account
    None,
  File "/home/debian8/dropbox-sdk-python/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/home/debian8/dropbox-sdk-python/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/home/debian8/dropbox-sdk-python/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/urllib3-1.21.1-py3.6.egg/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/urllib3-1.21.1-py3.6.egg/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/urllib3-1.21.1-py3.6.egg/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/urllib3-1.21.1-py3.6.egg/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/home/debian8/anaconda3/lib/python3.6/site-packages/urllib3-1.21.1-py3.6.egg/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.

```

**Comment by greg-db** [comment] 2017-06-30 14:32
[Cross-linking for reference: https://stackoverflow.com/questions/44836616/timeout-error-fo-dropbox-api-v2-with-python3-6 ]

This looks like a duplicate of #106. Can you check what version of `requests` is installed?

**Comment by yufeiluo** [comment] 2017-07-01 02:03
dropbox.Dropbox._API_VERSION
'2'

**Comment by yufeiluo** [comment] 2017-07-01 03:39
sudo  /usr/bin/pip3.6  install  -Iv  requests==2.15.1
To test in python3.6,same timeout error.
sudo  /usr/bin/pip3.6  uninstall   requests
sudo  /usr/bin/pip3.6  install  -Iv  requests==2.16.1
To test in python3.6,same timeout error.
sudo  /usr/bin/pip3.6  uninstall   requests
sudo  /usr/bin/pip3.6  install  -Iv  requests==2.17.1
To test in python3.6,same timeout error.

????

**Comment by dennissiemensma** [comment] 2017-07-01 10:05
I'm experiencing the same for calling `dbx.files_upload()`. And calling the same method of this ticket's reporter (`dbx.users_get_current_account()`) breaks it here as well.

Dropbox client version is `8.0.0`, the previous I was running (`7.3.1`) was working fine.

```
Python 3.5.2

requests==2.13.0
dropbox==8.0.0
```

**Comment by greg-db** [comment] 2017-07-03 17:21
@yufeiluo Apologies, you may actually have to go up to requests v2.18.1. Please try that out.

@dennissiemensma Likewise, please update to requests v2.18.1.

**Comment by dennissiemensma** [comment] 2017-07-03 17:46
Thanks, it fixes the problem here! Shouldn't the `pip install` install this dependency automatically btw?

**Comment by greg-db** [comment] 2017-07-03 17:51
@dennissiemensma Thanks for confirming that. And yes, it should. The dependency is listed [here](https://github.com/dropbox/dropbox-sdk-python/blob/master/setup.py#L28). I just tried it, and it did install requests v2.18.1 automatically for me when I ran `pip install dropbox`. If that didn't work for you, can you share your `pip` output, if you still have it?

**Comment by dennissiemensma** [comment] 2017-07-03 18:00
I see, but I mean.... if `2.18.x` fixes the issue, shouldn't be the minimum version be that, instead of `2.5.x` (as listed in the setup.py)? 
I have added `requests==2.18.1` in my own requirements.txt now, so it's fine for me anyway. Just wondering :]. 

Thanks again for the help, as I can now distribute the update for the dropbox-client v8 for my project.

**Comment by greg-db** [comment] 2017-07-03 18:03
I see, thanks for clarifying. Yes, we should probably just raise the requirement in general, since there were several bad `requests` versions. I'll ask the team to do so. Thanks!

**Comment by padremayi** [comment] 2017-08-27 10:44
python: 3.5.2
requests: 2.18.4
dropbox: 8.0.0

The problem is still present

**Comment by greg-db** [comment] 2017-10-11 18:37
We've updated the dependencies in [v8.4.0](https://github.com/dropbox/dropbox-sdk-python/releases/tag/v8.4.0).

**Closed by greg-db** 2017-10-11 18:37 UTC

**Comment by andreacat** [comment] 2018-04-14 23:51
python: 3.6.1
urllib3: 1.22
requests: 2.18.4
dropbox: 8.7.1

The problem is still present, whether I install urllib3 or not
