### ISSUE TITLE
Requests 2.14.2 not compatible?

### ISSUE THREAD

**Issue by anishathalye** [dropbox/dropbox-sdk-python#124] opened 2017-08-22 07:04 UTC
I maintain git-remote-dropbox, a package that depends on this SDK. Some people have pointed to an issue they believe is caused by dropbox-sdk-python not being compatible with Requests 2.14.2 (see https://github.com/anishathalye/git-remote-dropbox/issues/65#issuecomment-323613456), and that this could be resolved by requiring `requests >= 2.18.1`.

Is this a change you could make here? (that would be much nicer than working around this issue)

**Comment by greg-db** [comment] 2017-08-22 14:58
Thanks! Yes, there was an issue with some versions of the requests library. I'll ask the team to update the requirements on the Dropbox library accordingly.

**Comment by littleninja** [comment] 2017-08-22 16:33
Duplicate of #114?

**Comment by anishathalye** [comment] 2017-08-22 17:03
Yeah, looks like that's the same thing. Any chance it'll be fixed soon, or should I work around it?

**Comment by greg-db** [comment] 2017-08-22 17:33
That's correct Sarah, that appears to be a duplicate. I'm closing this in favor of that one. Thanks!

@anishathalye I don't have a timeline right now, so if this is blocking you, you may want to workaround it on your side for now. Apologies for the trouble!

**Closed by greg-db** 2017-08-22 17:33 UTC

**Comment by greg-db** [comment] 2017-10-11 18:37
We've updated the dependencies in [v8.4.0](https://github.com/dropbox/dropbox-sdk-python/releases/tag/v8.4.0).
